
server:
  port: 8080
  secret: ALC_DIARY_SECRET_KEY

  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      pattern: '%{yyyy-MM-dd HH:mm:ss}t %s "%r" %{User-Agent}i %{Referer}i %a %b %D "Authorization: %{Authorization}i"'

spring:
  application:
    name: alc-diary-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://alc-diary.ckupsgwzsqpk.ap-northeast-2.rds.amazonaws.com:3306/alc?serverTimezone=Asia/Seoul
    username: admin
    password: alcth123
    tomcat:
      max-active: 500
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  mvc:
    path match:
      matching-strategy: ant_path_matcher


feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000
        logger-level: NONE
      kakao-client:
        connect-timeout: 1000
        read-timeout: 10000
        logger-level: HEADERS