
server:
  port: 8080
  secret: ALC_DIARY_SECRET_KEY

spring:
  application:
    name: alc-diary-server
  jpa:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://alc-diary.ckupsgwzsqpk.ap-northeast-2.rds.amazonaws.com:3306/alc
    username: admin
    password: alcth123
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000
        logger-level: NONE
      kakao-client:
        connect-timeout: 1000
        read-timeout: 10000
        logger-level: HEADERS