name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with gradle
        run: ./gradlew clean build

#      - name: Login to Amazon ECR
#        id:
#        uses: aws-actions/amazon-ecr-login@v1
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.login-ecr.outputs.registry }}/taeyeongg:${ github.sha }}