name: CI-MAIN


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make Directory for deliver
        run: mkdir deploy

      - name: Copy jar
        run: cp ./build/libs/*.jar ./deploy/

      - name: Copy appspec
        run: cp appspec.yml ./deploy/

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip ./deploy/

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://alc-diary/$GITHUB_SHA.zip

