name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with gradle
        run: ./gradlew clean build

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/alc-diary:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/alc-diary:latest

      - name: Deploy to EC2
        id: deploy-ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          password: alc-diary
          port: 22
          script: |
            docker rm -f $(docker ps -aq)
            docker pull ${{ steps.login-ecr.outputs.registry }}/alc-diary:latest
            docker run --rm -d -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/alc-diary:latest