name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/kakao-login

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with gradle
        run: ./gradlew clean build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/alc-diary:latest

      - name: Deploy to EC2
        id: deploy-ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_SECRET_KEY }}
          port: 22
          script: |
            docker rm -f $(docker ps -aq)
            docker rmi $(docker images -q)
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/alc-diary:latest
            docker run -d -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/alc-diary:latest