name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with gradle
        run: ./gradlew clean build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/alc-diary:latest

      - name: Deploy to EC2
        id: deploy-ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_SECRET_KEY }}
          port: 22
          script: |
            docker rm -f $(docker ps -aq)
            docker rmi $(docker images -q)
            docker run \
            --name alc \
            -d \
            -p 8080:8080 \
            -v /var/log/alc:/logs \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e DB_URL=${{ secrets.DB_URL }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
            -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
            -e LOG_DIR=${{ secrets.LOG_DIR }} \
            -e TOMCAT_ACCESS_LOG_DIR=${{ secrets.TOMCAT_ACCESS_LOG_DIR }} \
            -e TOMCAT_ACCESS_LOG_PATTERN=${{ secrets.TOMCAT_ACCESS_LOG_PATTERN }} \
            -e SLACK_WEBHOOK_URI=${{ secrets.SLACK_WEBHOOK_URI }} \
            -e SLACK_TOKEN=${{ secrets.SLACK_TOKEN }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/alc-diary:latest
